import { createHash } from 'crypto';
import { Question } from '../modules/questions/question.model';

const bank = [
  { subtopic:'URL shortening', difficulty:'HARD', question:'Design a URL-shortening service that handles high read traffic, custom aliases, expiration, and click analytics.', concepts:['id generation','redirects','caching','sharding'], archetype:'SCALABILITY', detailedAnswer:'Start by clarifying write volume, redirect latency, retention, and availability targets. Create a short code with a collision-safe distributed ID or an encoded unique key, store the mapping durably, and serve redirects from a cache backed by a partitioned database. Make creation idempotent where appropriate, protect custom aliases with uniqueness checks, and treat analytics as an asynchronous event stream so they do not slow redirects. Discuss hot-key caching, expiration, abuse controls, and how replication and backups affect consistency and recovery.' },
  { subtopic:'Rate limiting', difficulty:'MEDIUM', question:'Design a distributed rate limiter for an API used by many application instances, including bursts and per-customer quotas.', concepts:['token bucket','distributed state','atomicity','failure policy'], archetype:'DESIGN', detailedAnswer:'First define the quota dimensions, time windows, burst allowance, and what should happen when the limiter is unavailable. A token bucket supports controlled bursts while bounding the average rate. Store bucket state in a shared low-latency system and update it atomically, using server time and an expiry to reclaim idle keys. Partition by customer or API key, protect the store from hot tenants, and return a clear retry hint. Compare fail-open and fail-closed behavior, monitor rejection rates and storage latency, and test clock skew and concurrent requests.' },
  { subtopic:'News feed', difficulty:'HARD', question:'Design a personalized news feed for millions of users, balancing freshness, ranking quality, and predictable latency.', concepts:['fanout','ranking','caching','pagination'], archetype:'SCALABILITY', detailedAnswer:'Clarify feed size, freshness, personalization, and read/write ratios. A hybrid fanout model writes feeds for ordinary accounts but merges followed-author streams at read time for exceptionally high-fanout authors. Store ranked feed references separately from canonical posts, cache the first page, and use cursor pagination to avoid unstable offsets. Ranking can combine recency and relevance while respecting privacy and block lists. Discuss backfills, deleted content, duplicate suppression, cache invalidation, and graceful degradation when ranking dependencies are slow.' },
  { subtopic:'Chat service', difficulty:'HARD', question:'Design a one-to-one and group messaging service with ordered delivery, offline users, and multi-device synchronization.', concepts:['websockets','message ordering','queues','delivery state'], archetype:'DESIGN', detailedAnswer:'Establish message volume, group-size limits, retention, and delivery guarantees. Maintain persistent client connections through gateways, authenticate them, and route messages through a durable per-conversation stream or partition so ordering has a clear scope. Persist before acknowledging, then fan out to online devices and queue notifications for offline users. Use idempotency keys for retries, explicit delivery/read state, and synchronization cursors for reconnecting devices. Address group fanout, encryption boundaries, abuse controls, regional failover, and what ordering guarantees are intentionally not provided.' },
  { subtopic:'Object storage', difficulty:'HARD', question:'Design a highly available object-storage service for large uploads, downloads, metadata lookup, and lifecycle deletion.', concepts:['multipart upload','metadata','replication','integrity'], archetype:'SCALABILITY', detailedAnswer:'Separate object bytes from metadata. Upload large objects in independently retryable parts, verify checksums, and publish the object only after all required parts are durable. Store metadata in a strongly consistent index for ownership and lifecycle state, while object chunks use replicated or erasure-coded storage across failure domains. Downloads should support range requests and signed authorization. Define consistency for overwrite and delete, garbage-collect abandoned uploads, and plan repair, versioning, quotas, encryption, and regional disaster recovery.' },
  { subtopic:'Search autocomplete', difficulty:'MEDIUM', question:'Design low-latency search autocomplete that handles popular prefixes, typo tolerance, and frequent index updates.', concepts:['prefix index','ranking','caching','index freshness'], archetype:'DESIGN', detailedAnswer:'Clarify language, request volume, freshness, and typo-tolerance requirements. Build a prefix-oriented index from normalized terms and rank suggestions using relevance, popularity, and recency. Cache hot prefixes at the edge or service tier, with bounded result lists and short invalidation windows. Publish index updates through a stream and version snapshots so readers can switch atomically. Protect against very short expensive prefixes, apply privacy and abuse filters, measure tail latency, and consider a fallback to the last-known index during rebuilds.' },
  { subtopic:'Payment processing', difficulty:'HARD', question:'Design a payment-processing workflow that safely handles retries, duplicate requests, delayed provider responses, and reconciliation.', concepts:['idempotency','state machine','ledger','reconciliation'], archetype:'FAILURE_SCENARIO', detailedAnswer:'Model each payment as an explicit state machine and require an idempotency key for client retries. Persist the intent and an outbox event transactionally, then call the external processor asynchronously. Treat timeouts as unknown outcomes rather than failures: query or reconcile with the provider before retrying a charge. Keep an immutable ledger of financial movements, make webhook handling idempotent, and reconcile internal records against provider reports. Discuss authorization versus capture, refunds, auditability, access control, and operational recovery procedures.' },
  { subtopic:'Distributed cache', difficulty:'MEDIUM', question:'Design a distributed cache for a read-heavy service and explain how you would handle hot keys, stale data, and cache-node failures.', concepts:['cache-aside','eviction','hot keys','consistency'], archetype:'TRADE_OFF', detailedAnswer:'Choose a cache-aside or write-through policy based on the acceptable staleness and write path. Define key design, TTLs, eviction, and invalidation semantics before tuning capacity. Prevent stampedes with request coalescing, jittered expiry, or bounded stale-while-revalidate behavior. Replicate or shard according to availability and working-set size, and mitigate hot keys with local caches or controlled replication. Monitor hit rate alongside origin load and tail latency; a high hit rate alone is not proof of correctness. Define safe behavior during cache loss and warm-up.' },
  { subtopic:'Notification delivery', difficulty:'MEDIUM', question:'Design a notification platform that sends email, push, and SMS reliably while respecting user preferences and provider limits.', concepts:['queues','idempotency','delivery state','backpressure'], archetype:'DESIGN', detailedAnswer:'Separate notification intent from channel delivery. Store an idempotent request and enqueue it durably, then let channel-specific workers apply templates, user preferences, quiet hours, and provider rate limits. Track delivery attempts and provider callbacks as state transitions, with bounded retries and a dead-letter path for permanent errors. Prioritize urgent traffic, prevent duplicate sends, and expose delivery latency and failure rates. Discuss provider outages, consent changes while messages are queued, regional failover, and safe replay.' },
  { subtopic:'Inventory reservation', difficulty:'HARD', question:'Design an inventory reservation service that prevents overselling during flash sales while allowing reservations to expire.', concepts:['atomic reservation','consistency','expiration','contention'], archetype:'FAILURE_SCENARIO', detailedAnswer:'Define whether inventory is globally or regionally partitioned and whether temporary unavailability is preferable to overselling. Represent stock and reservations with atomic conditional updates or a serialized per-item command stream. Give each reservation an idempotency key and expiry, and ensure expiration releases stock exactly once. High-demand items create hot partitions, so consider admission control, queueing, or preallocated regional quotas. Reconcile counters against reservation records, and test retries, delayed expiry workers, payment timeouts, and partial failures.' },
  { subtopic:'Video streaming', difficulty:'HARD', question:'Design a video-streaming service that supports uploads, transcoding, adaptive playback, and global content delivery.', concepts:['transcoding pipeline','object storage','CDN','job orchestration'], archetype:'SCALABILITY', detailedAnswer:'Treat upload, processing, catalog metadata, and playback as separate paths. Accept resumable uploads into object storage, emit a durable processing job, and create multiple bitrate renditions asynchronously with retryable workers. Publish a video only when required renditions and metadata are ready. Serve manifests and chunks through a CDN with authorization and cache rules. Track processing state and quality, isolate expensive transcodes, and plan retries, poison jobs, deletion propagation, regional replication, DRM boundaries, and cost controls.' },
  { subtopic:'Multi-tenant analytics', difficulty:'HARD', question:'Design a multi-tenant analytics pipeline that ingests events at high volume and supports isolated, near-real-time customer queries.', concepts:['stream processing','tenant isolation','partitioning','late events'], archetype:'SCALABILITY', detailedAnswer:'Clarify event volume, query freshness, retention, and tenant isolation requirements. Validate and authenticate events at ingestion, partition the stream to preserve only the ordering needed, and use idempotent processing with event-time windows for late arrivals. Store raw events for replay and derived aggregates for fast queries. Enforce tenant-aware authorization at every query boundary, apply quotas to noisy tenants, and avoid cross-tenant cache leakage. Monitor lag and data quality, support schema evolution, and document replay and deletion behavior.' },
  { subtopic:'Database migration', difficulty:'HARD', question:'Plan a zero-downtime migration of a large production database to a new schema while old and new application versions overlap.', concepts:['expand-contract','dual writes','backfill','rollback'], archetype:'TRADE_OFF', detailedAnswer:'Use an expand-and-contract sequence. Add backward-compatible schema first, deploy readers that tolerate both forms, and backfill in bounded batches with checkpoints and rate limits. During transition, define one authoritative write path and verify parity; uncontrolled dual writes can diverge. Measure lag and correctness, then move reads gradually behind a feature flag. Keep rollback possible until validation is complete, and remove old fields only after all application versions and background jobs have migrated. Include lock impact, data repair, observability, and abort criteria.' },
];

function normalizedHash(text:string):string {
  const normalized = text.normalize('NFKC').toLowerCase().replace(/[^\p{L}\p{N}]+/gu, ' ').trim().replace(/\s+/g, ' ');
  return createHash('sha256').update(normalized).digest('hex');
}

/** Idempotently make a useful system-design bank available on every install. */
export async function seedSystemDesignQuestions():Promise<{ inserted:number; skipped:number }> {
  let inserted = 0, skipped = 0;
  for (const item of bank) {
    const hash = normalizedHash(item.question);
    const question = { ...item, topic:'System design', questionType:'SYSTEM_DESIGN',
      estimatedAnswerTimeSeconds:420, provenance:'CURATED', qualityStatus:'approved', qualityScore:0.8,
      interviewPriority:'HIGH', resumeRelevance:'MEDIUM', expectedAnswerDepth:'DEEP',
      isSystemDesign:true, isHidden:false, isDeprecated:false, isCoding:false, isProjectInterview:false,
      normalizedHash:hash, tags:['system-design','curated'],
    };
    try {
      const result = await Question.updateOne({ normalizedHash:hash }, { $setOnInsert:question }, { upsert:true });
      if (result.upsertedCount) inserted++; else skipped++;
    } catch (error:any) {
      // Multiple backend replicas may seed the same reference question on
      // startup; the unique normalized-hash index makes that race harmless.
      if (error.code === 11000) skipped++;
      else throw error;
    }
  }
  return { inserted, skipped };
}
